sudo: required

services:
  - docker

before_install:
  - docker build -t lioneltay/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run lioneltay/react-text npm test -- --coverage

after_success:
  - docker build -t lioneltay/multi-client ./client
  - docker build -t lioneltay/multi-nginx ./nginx
  - docker build -t lioneltay/multi-server ./server
  - docker build -t lioneltay/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lioneltay/multi-client
  - docker push lioneltay/multi-server
  - docker push lioneltay/multi-nginx
  - docker push lioneltay/multi-worker

deploy:
